require("kernel.objects.cc_extends")

require("kernel.objects.basic.CNode")
require("kernel.objects.basic.CLayer")
require("kernel.objects.basic.CScene")
require("kernel.objects.basic.CSprite")
require("kernel.objects.basic.CScale9Sprite")
require("kernel.objects.basic.CImageView")
require("kernel.objects.basic.CButton")
require("kernel.objects.basic.CEditBox")
require("kernel.objects.basic.CLabel")

require("kernel.objects.gui.compRichText")
require("kernel.objects.gui.compList")
require("kernel.objects.gui.compGrid")
require("kernel.objects.gui.compTree")
require("kernel.objects.gui.compTabGroup")
require("kernel.objects.gui.compMergeButton")
require("kernel.objects.gui.html")
require("kernel.objects.gui.HtmlText")
require("kernel.objects.gui.ScrollHtmlText")
require("kernel.objects.gui.BaseUI")

require("kernel.objects.effect.EffectSeq")
