module("ui",package.seeall)

clsSelectType = class("clsSelectType",clsBaseUI)
function clsSelectType:ctor(parent)
    clsBaseUI.ctor(self,parent,"uistu/SelectType.csb")
    self:InUiEvent()
end

function clsSelectType:InUiEvent()
    utils.RegClickEvent(self.Button_3_6,function()
        g_EventMgr:FireEvent("rebatetype",1)
        self:removeSelf()
    end)
    utils.RegClickEvent(self.Button_3_5,function()
        g_EventMgr:FireEvent("rebatetype",2)
        self:removeSelf()
    end)
    utils.RegClickEvent(self.Button_3_4,function()
        g_EventMgr:FireEvent("rebatetype",3)
        self:removeSelf()
    end)
    utils.RegClickEvent(self.Button_3,function()
        g_EventMgr:FireEvent("rebatetype",4)
        self:removeSelf()
    end)
    utils.RegClickEvent(self.Button_3_0,function()
        g_EventMgr:FireEvent("rebatetype",5)
        self:removeSelf()
    end)
    utils.RegClickEvent(self.Button_3_1,function()
        g_EventMgr:FireEvent("rebatetype",6)
        self:removeSelf()
    end)
    utils.RegClickEvent(self.Button_3_2,function()
        g_EventMgr:FireEvent("rebatetype",7)
        self:removeSelf()
    end)
    utils.RegClickEvent(self.Button_3_3,function()
        self:removeSelf()
    end)
end