require("app.mgr.SettingManager")
require("app.mgr.UserDefaultData")
require("app.mgr.AdvertiseMgr")
require("app.mgr.RedPointMgr")
require("app.mgr.StateMachine")
require("app.mgr.Game")
require("app.mgr.UserEntity")
require("app.mgr.GlobalEvents")
