local DRAGON_CFG = {}

DRAGON_CFG.domain_list = {
    "https://www.wpub1dkjflsdakjfsdkgdfjsdfj.com",
    "https://www.wpub2dkjflsdakjfsdkgdfjsdfj.com",
    "https://www.wpub3dkjsadfsadfgklfjsdfj.com",
    "https://www.wpub5dkjsadsadfybboixm.com",
}

DRAGON_CFG.highdef_domain = "https://www.yikaiapi.com"

DRAGON_CFG.WS_ERROR_TBL = {
    [0] = "消息体格式错误",
    [1] = "token错误",
    [2] = "未登陆",
    [3] = "被禁言",
    [4] = "聊天室禁言",
    [10] = "发送内容包含违规字词",
    [11] = "VIP发言限制",
    [12] = "VIP每分钟发言限制",
    [13] = "VIP分享限制",
}

DRAGON_CFG.EMOJI = {
        { File="emoji_00.png", Tag="[微笑]" },
        { File="emoji_01.png", Tag="[撇嘴]" },
        { File="emoji_02.png", Tag="[色]" },
        { File="emoji_03.png", Tag="[发呆]" },
        { File="emoji_04.png", Tag="[得意]" },
        { File="emoji_05.png", Tag="[流泪]" },
        { File="emoji_06.png", Tag="[害羞]" },
        { File="emoji_07.png", Tag="[闭嘴]" },
        { File="emoji_08.png", Tag="[睡]" },
        { File="emoji_09.png", Tag="[大哭]" },
        { File="emoji_10.png", Tag="[尴尬]" },
        { File="emoji_11.png", Tag="[发怒]" },
        { File="emoji_12.png", Tag="[调皮]" },
        { File="emoji_13.png", Tag="[呲牙]" },
        { File="emoji_14.png", Tag="[惊讶]" },
        { File="emoji_15.png", Tag="[难过]" },
        { File="emoji_16.png", Tag="[酷]" },
        { File="emoji_17.png", Tag="[冷汗]" },
        { File="emoji_18.png", Tag="[抓狂]" },
        { File="emoji_19.png", Tag="[吐]" },
        { File="emoji_20.png", Tag="[偷笑]" },
        { File="emoji_21.png", Tag="[愉快]" },
        { File="emoji_22.png", Tag="[白眼]" },
        { File="emoji_23.png", Tag="[傲慢]" },
        { File="emoji_24.png", Tag="[饥饿]" },
        { File="emoji_25.png", Tag="[困]" },
        { File="emoji_26.png", Tag="[惊恐]" },
        { File="emoji_27.png", Tag="[流汗]" },
        { File="emoji_28.png", Tag="[憨笑]" },
        { File="emoji_29.png", Tag="[悠闲]" },
        { File="emoji_30.png", Tag="[奋斗]" },
        { File="emoji_31.png", Tag="[咒骂]" },
        { File="emoji_32.png", Tag="[疑问]" },
        { File="emoji_33.png", Tag="[嘘]" },
        { File="emoji_34.png", Tag="[晕]" },
        { File="emoji_35.png", Tag="[疯了]" },
        { File="emoji_36.png", Tag="[衰]" },
        { File="emoji_37.png", Tag="[骷髅]" },
        { File="emoji_38.png", Tag="[敲打]" },
        { File="emoji_39.png", Tag="[再见]" },
        { File="emoji_40.png", Tag="[擦汗]" },
        { File="emoji_41.png", Tag="[抠鼻]" },
        { File="emoji_42.png", Tag="[鼓掌]" },
        { File="emoji_43.png", Tag="[糗大了]" },
        { File="emoji_44.png", Tag="[坏笑]" },
        { File="emoji_45.png", Tag="[左哼哼]" },
        { File="emoji_46.png", Tag="[右哼哼]" },
        { File="emoji_47.png", Tag="[哈欠]" },
        { File="emoji_48.png", Tag="[鄙视]" },
        { File="emoji_49.png", Tag="[委屈]" },
        { File="emoji_50.png", Tag="[快哭]" },
        { File="emoji_51.png", Tag="[阴险]" },
        { File="emoji_52.png", Tag="[亲亲]" },
        { File="emoji_53.png", Tag="[吓]" },
        { File="emoji_54.png", Tag="[可怜]" },
        { File="emoji_55.png", Tag="[菜刀]" },
        { File="emoji_56.png", Tag="[西瓜]" },
        { File="emoji_57.png", Tag="[啤酒]" },
        { File="emoji_58.png", Tag="[篮球]" },
        { File="emoji_59.png", Tag="[乒乓]" },
        { File="emoji_60.png", Tag="[咖啡]" },
        { File="emoji_61.png", Tag="[饭]" },
        { File="emoji_62.png", Tag="[猪头]" },
        { File="emoji_63.png", Tag="[玫瑰]" },
        { File="emoji_64.png", Tag="[凋谢]" },
        { File="emoji_65.png", Tag="[嘴唇]" },
        { File="emoji_66.png", Tag="[爱心]" },
        { File="emoji_67.png", Tag="[心碎]" },
        { File="emoji_68.png", Tag="[蛋糕]" },
        { File="emoji_69.png", Tag="[闪电]" },
        { File="emoji_70.png", Tag="[炸弹]" },
        { File="emoji_71.png", Tag="[刀]" },
        { File="emoji_72.png", Tag="[足球]" },
        { File="emoji_73.png", Tag="[瓢虫]" },
        { File="emoji_74.png", Tag="[便便]" },
        { File="emoji_75.png", Tag="[月亮]" },
        { File="emoji_76.png", Tag="[太阳]" },
        { File="emoji_77.png", Tag="[礼物]" },
        { File="emoji_78.png", Tag="[拥抱]" },
        { File="emoji_79.png", Tag="[强]" },
        { File="emoji_80.png", Tag="[弱]" },
        { File="emoji_81.png", Tag="[握手]" },
        { File="emoji_82.png", Tag="[胜利]" },
        { File="emoji_83.png", Tag="[抱拳]" },
        { File="emoji_84.png", Tag="[勾引]" },
        { File="emoji_85.png", Tag="[拳头]" },
        { File="emoji_86.png", Tag="[差劲]" },
        { File="emoji_87.png", Tag="[爱你]" },
        { File="emoji_88.png", Tag="[NO]" },
        { File="emoji_89.png", Tag="[OK]" },
        { File="emoji_90.png", Tag="[爱情]" },
        { File="emoji_91.png", Tag="[飞吻]" },
        { File="emoji_92.png", Tag="[跳跳]" },
        { File="emoji_93.png", Tag="[发抖]" },
        { File="emoji_94.png", Tag="[怄火]" },
        { File="emoji_95.png", Tag="[转圈]" },
        { File="emoji_96.png", Tag="[磕头]" },
        { File="emoji_97.png", Tag="[回头]" },
        { File="emoji_98.png", Tag="[跳绳]" },
        { File="emoji_99.png", Tag="[投降]" },
        { File="emoji_100.png", Tag="[激动]" },
        { File="emoji_101.png", Tag="[乱舞]" },
        { File="emoji_102.png", Tag="[献吻]" },
        { File="emoji_103.png", Tag="[左太极]" },
        { File="emoji_104.png", Tag="[右太极]" },
}
DRAGON_CFG.EMOJI_BY_TAG = {}
for _, info in ipairs(DRAGON_CFG.EMOJI) do
    DRAGON_CFG.EMOJI_BY_TAG[info.Tag] = info
end

return DRAGON_CFG
