return {
	[1001] = {
		["BuffType"] = 1001,
		["BuffName"] = "加血",
		["Desc"] = "瞬间加血",
		["Icon"] = "res/uistu/icons/buff/buff_huifu.png",
		["PiaoZi"] = "",
		["MutexDoTips"] = true,
		["MaxOverlap"] = -1,
		["ReplaceAble"] = false,
		["Prop"] = "HP",
		["Value"] = 6000,
		["Percent"] = false,
		["KeepTime"] = 0,
	},
	[1002] = {
		["BuffType"] = 1002,
		["BuffName"] = "回血",
		["Desc"] = "每回合加血",
		["Icon"] = "res/uistu/icons/buff/buff_huifu.png",
		["PiaoZi"] = "res/uistu/fight/pz_huifu.png",
		["MutexDoTips"] = true,
		["MaxOverlap"] = 12,
		["ReplaceAble"] = false,
		["Prop"] = "HP",
		["Value"] = 200,
		["Percent"] = false,
		["KeepTime"] = 3,
	},
	[1003] = {
		["BuffType"] = 1003,
		["BuffName"] = "中毒",
		["Desc"] = "持续掉血",
		["Icon"] = "res/uistu/icons/buff/buff_zhongdu.png",
		["PiaoZi"] = "res/uistu/fight/pz_zhongdu.png",
		["MutexDoTips"] = true,
		["MaxOverlap"] = 1,
		["ReplaceAble"] = false,
		["Prop"] = "HP",
		["Value"] = -250,
		["Percent"] = false,
		["KeepTime"] = 3,
	},
	
	[2001] = {
		["BuffType"] = 2001,
		["BuffName"] = "增加血量上限",
		["Desc"] = "增加血量上限",
		["Icon"] = "res/uistu/icons/buff/buff_maxhp_up.png",
		["PiaoZi"] = "res/uistu/fight/pz_xueliangup.png",
		["MutexDoTips"] = true,
		["MaxOverlap"] = 10,
		["ReplaceAble"] = false,
		["Prop"] = "MaxHP",
		["Value"] = 100,
		["Percent"] = false,
		["KeepTime"] = 0,
	},
	[2002] = {
		["BuffType"] = 2002,
		["BuffName"] = "降低血量上限",
		["Desc"] = "降低血量上限",
		["Icon"] = "res/uistu/icons/buff/buff_maxhp_down.png",
		["PiaoZi"] = "res/uistu/fight/pz_xueliangdown.png",
		["MutexDoTips"] = true,
		["MaxOverlap"] = 10,
		["ReplaceAble"] = false,
		["Prop"] = "MaxHP",
		["Value"] = -100,
		["Percent"] = false,
		["KeepTime"] = 0,
	},
	
	[3001] = {
		["BuffType"] = 3001,
		["BuffName"] = "提升攻击",
		["Desc"] = "增加攻击力",
		["Icon"] = "res/uistu/icons/buff/buff_gongji_up.png",
		["PiaoZi"] = "res/uistu/fight/pz_gongjiup.png",
		["MutexDoTips"] = true,
		["MaxOverlap"] = 10,
		["ReplaceAble"] = false,
		["Prop"] = "PhyAtk",
		["Value"] = 0.5,
		["Percent"] = true,
		["KeepTime"] = 3,
	},
	[3002] = {
		["BuffType"] = 3002,
		["BuffName"] = "降低攻击",
		["Desc"] = "降低攻击力",
		["Icon"] = "res/uistu/icons/buff/buff_gongji_down.png",
		["PiaoZi"] = "res/uistu/fight/pz_gongjidown.png",
		["MutexDoTips"] = true,
		["MaxOverlap"] = 10,
		["ReplaceAble"] = false,
		["Prop"] = "PhyAtk",
		["Value"] = -0.2,
		["Percent"] = true,
		["KeepTime"] = 2,
	},
	
	[4001] = {
		["BuffType"] = 4001,
		["BuffName"] = "提升防御",
		["Desc"] = "增加防御力",
		["Icon"] = "res/uistu/icons/buff/buff_fanji.png",
		["PiaoZi"] = "",
		["MutexDoTips"] = true,
		["MaxOverlap"] = 10,
		["ReplaceAble"] = false,
		["Prop"] = "PhyDef",
		["Value"] = 0.1,
		["Percent"] = true,
		["KeepTime"] = 3,
	},
	[4002] = {
		["BuffType"] = 4002,
		["BuffName"] = "降低防御",
		["Desc"] = "降低防御力",
		["Icon"] = "res/uistu/icons/buff/buff_fanji.png",
		["PiaoZi"] = "",
		["MutexDoTips"] = true,
		["MaxOverlap"] = 10,
		["ReplaceAble"] = false,
		["Prop"] = "PhyDef",
		["Value"] = -0.1,
		["Percent"] = true,
		["KeepTime"] = 2,
	},
	
	[5001] = {
		["BuffType"] = 5001,
		["BuffName"] = "免伤",
		["Desc"] = "降低伤害",
		["Icon"] = "res/uistu/icons/buff/buff_mianshang.png",
		["PiaoZi"] = "res/uistu/fight/pz_shanghaijianmian.png",
		["MutexDoTips"] = true,
		["MaxOverlap"] = 10,
		["ReplaceAble"] = false,
		["Prop"] = "",
		["Value"] = -0.1,
		["Percent"] = true,
		["KeepTime"] = 3,
	},
	[5002] = {
		["BuffType"] = 5002,
		["BuffName"] = "铁壁",
		["Desc"] = "伤害变一血",
		["Icon"] = "res/uistu/icons/buff/buff_tiebi.png",
		["PiaoZi"] = "res/uistu/fight/pz_tiebi.png",
		["MutexDoTips"] = true,
		["MaxOverlap"] = 10,
		["ReplaceAble"] = false,
		["Prop"] = "",
		["Value"] = 1,
		["Percent"] = false,
		["KeepTime"] = 3,
	},
}