--
require("app_arpg.modules.logon.view.LoginScene")
require("app_arpg.modules.logon.view.LoginByAccountUI")
require("app_arpg.modules.logon.view.LoginUI")
require("app_arpg.modules.logon.view.RegistUI")
--
require("app_arpg.modules.hall.view.RestScene")
require("app_arpg.modules.hall.view.MainUI")
--
require("app_arpg.modules.benefit.view.BenefitUI")
--
require("app_arpg.modules.person.view.PersonUI")
require("app_arpg.modules.person.view.PersonalUI")
--
require("app_arpg.modules.shop.view.ShopUI")
--
require("app_arpg.modules.rank.view.RankUI")
--
require("app_arpg.modules.signin.view.SigninUI")
--
require("app_arpg.modules.task.view.TaskUI")
--
require("app_arpg.modules.vip.view.VipUI")
require("app_arpg.modules.vip.view.FirstRechargeUI")
--
require("app_arpg.modules.wheel.view.WheelUI")
--
require("app_arpg.modules.share.view.ShareUI")
--
require("app_arpg.modules.others.view.MoreUI")
