require("app.arpg.common.UserEntity")
require("app.arpg.common.GlobalEvents")

require("app.arpg.common.mgr.UserDefaultData")
require("app.arpg.common.mgr.AdvertiseMgr")
require("app.arpg.common.mgr.RedPointMgr")
require("app.arpg.common.mgr.StateMachine")

require("app.arpg.common.view.HeadView")
require("app.arpg.common.view.ContainerInterface")
require("app.arpg.common.view.InnerGrid")
require("app.arpg.common.view.AutoGrid")
require("app.arpg.common.view.Field")
require("app.arpg.common.view.ConfirmDlg")
require("app.arpg.common.view.ConfirmDlg2")
require("app.arpg.common.view.PicNumber")
require("app.arpg.common.view.PicLabel")
require("app.arpg.common.view.gmUI")
